---
- name: ex 5
  hosts: juniper
  gather_facts: False
  tasks:


    - name: show interfaces on junos devices
      junos_command:
        commands: show interfaces terse
      register: interfaces

    - debug:
        msg: "{{ interfaces }}"
