- name: ex2
  hosts: arista
  gather_facts: False
  vars:
    ansible_user: pyclass
    ansible_ssh_pass: "{{ lookup('env', 'ANSIBLE_PASSWORD')}}"
  tasks:

  - name: show vlan on EOS
    eos_command:
      commands: show vlan
    register: show_vlan

  - debug:
      var: show_vlan

# ansible-playbook -i ansible-hosts.ini 2.yml
