- name: ex1
  hosts: nxos
  gather_facts: False
  vars:
    fsm_template: "cisco_nxos_show_lldp_neighbors.textfsm"
  tasks:
    - name : show lldp neighbors on NXOS
      nxos_command:
        commands: show lldp neighbors
      register: output

    - set_fact:
        show_lldp_neighbors: "{{ output.stdout[0] | parse_cli_textfsm(fsm_template) }}"

    - set_fact:
        lldp_map: "{{ lldp_map | default({}) | combine({item['LOCAL_INTERFACE']:item['NEIGHBOR']}) }}"
      loop: "{{ show_lldp_neighbors }}"

    - debug:
        var: lldp_map
