---
- name: ex2
  hosts: nxos1
  gather_facts: False

  tasks:
    - name: show vlan id
      nxos_command:
        commands: show vlan id {{ item }}
      loop:
        - 1
        - 2
        - 3
        - 4
      register: vlans

    - debug:
        var: vlans.results[-1].stdout_lines
