---
- name: ex3
  hosts: cisco
  vars:
    domain_name: bogus.com
    ntp_server1: 130.126.24.24
    ntp_server2: 152.2.21.1
    dns_server1: 8.8.8.8
    dns_server2: 8.8.4.4
  gather_facts: True
  tasks:

  - name: Settings for IOS devices
    import_tasks: ios_settings.yml
    when: ansible_facts.net_iostype == "IOS"

  - name: Settings for IOS-XE devices
    import_tasks: iosxe_settings.yml
    when: ansible_facts.net_iostype == "IOS-XE"

