---
- name: ex3
  hosts: cisco1:cisco2
  gather_facts: False
  tasks:

  - name: show lldp neighbors
    ios_command:
      commands: show lldp neighbors
    register: show_lldp_neighbors

  - name: filter twb-sf-hpsw1
    set_fact:
      lldp_entry: "{{ item }}"
    loop: "{{ show_lldp_neighbors.stdout_lines[0] }}"
    when: "'twb-sf-hpsw1' in item"

  - name: extract items
    set_fact:
         remote_device: "{{ lldp_entry.split()[0] }}"
         local_intf: "{{ lldp_entry.split()[1] }}"
         remote_intf: "{{ lldp_entry.split()[-1] }}"

  - debug:
      msg:
        - "Remote device : {{ remote_device }}"
        - "Local intf : {{ local_intf }}"
        - "Remote intf : {{ remote_intf }}"

