---
- name: ex2
  hosts: cisco:arista:nxos
  gather_facts: True
  tasks:

  - name: config for IOS devices
    cli_config:
      config: |
        ip domain name {{domain_name}}
        ntp server {{ntp_server1}}
        ntp server {{ntp_server2}}
        ip name-server {{dns_server1}}
        ip name-server {{dns_server2}}
    when: 
        - ansible_network_os=="ios"
        - ansible_facts.net_iostype=="IOS"


  - name: config for IOS XE devices
    cli_config:
      config: |
        ip domain name {{domain_name}}
        ntp server {{ntp_server1}}
        ntp server {{ntp_server2}}
        ip name-server {{dns_server1}} {{dns_server2}}
    when: 
        - ansible_network_os=="ios"
        - ansible_facts.net_iostype=="IOS-XE"

  - name: config for Arista devices
    cli_config:
      config: |
        ip domain-name {{domain_name}}
        ntp server {{ntp_server1}}
        ntp server {{ntp_server2}}
        ip name-server {{dns_server1}}
        ip name-server {{dns_server2}}
    when: ansible_network_os=="eos"

  - name: config for NXOS devices
    cli_config:
      config: |
        ip domain-name {{domain_name}}
        ntp server {{ntp_server1}} use-vrf management
        ntp server {{ntp_server2}} use-vrf default
        ip name-server {{dns_server1}} {{dns_server2}}
    when: ansible_network_os=="nxos"


