- name: ex4b
  hosts: nxos
  vars:
    command: show version
  collections:
    - clay584.genie
  gather_facts: False
  tasks:

  - name: show interface on NXOS
    nxos_command:
      commands: "{{ command }}"
    register: output

  - set_fact:
      output_struct: "{{ output.stdout[0] | clay584.genie.parse_genie(command=command, os='nxos') }}"

  - set_fact:
      software_ver: "{{ output_struct['platform']['software']['system_version'] }}"

  - debug:
      msg: "Software version: {{ software_ver }}"
