---
- name: ex 6
  hosts: arista
  gather_facts: False
  tasks:

    - name: Using Arista eos_command module to show arp
      eos_command:
        commands: show ip arp
      register: output


    - debug:
        msg: "{{ output }}"

