---
- name: ex1
  hosts: cisco:arista:nxos
  gather_facts: True
  tasks:

  - name: config for IOS devices
    ios_config:
      lines:
        - "ip domain name {{domain_name}}"
        - "ntp server {{ntp_server1}}"
        - "ntp server {{ntp_server2}}"
        - "ip name-server {{dns_server1}}"
        - "ip name-server {{dns_server2}}"
    when: 
        - ansible_network_os=="ios"
        - ansible_facts.net_iostype=="IOS"


  - name: config for IOS XE devices
    ios_config:
      lines:
        - "ip domain name {{domain_name}}"
        - "ntp server {{ntp_server1}}"
        - "ntp server {{ntp_server2}}"
        - "ip name-server {{dns_server1}} {{dns_server2}}"
    when: 
        - ansible_network_os=="ios"
        - ansible_facts.net_iostype=="IOS-XE"

  - name: config for Arista devices
    eos_config:
      lines:
        - "ip domain-name {{domain_name}}"
        - "ntp server {{ntp_server1}}"
        - "ntp server {{ntp_server2}}"
        - "ip name-server {{dns_server1}}"
        - "ip name-server {{dns_server2}}"
    when: ansible_network_os=="eos"

  - name: config for NXOS devices
    nxos_config:
      lines:
        - "ip domain-name {{domain_name}}"
        - "ntp server {{ntp_server1}} use-vrf management"
        - "ntp server {{ntp_server2}} use-vrf default"
        - "ip name-server {{dns_server1}} {{dns_server2}}"
    when: ansible_network_os=="nxos"


