---
- name: ex1
  hosts: juniper
  gather_facts: False
  tasks:

  - name: config for SRX devices
    junos_config:
      lines:
        - "set system domain-name {{domain_name}}"
        - "set system ntp server {{ntp_server1}}"
        - "set system ntp server {{ntp_server2}}"
        - "set system name-server {{dns_server1}}"
        - "set system name-server {{dns_server2}}"
    when: ansible_network_os=="junos"


